apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: openttd
  name: openttd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openttd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openttd
    spec:
      containers:
      - image: gdekoenigsberg/showdown-openttd:latest
        name: showdown-openttd-image
        env:
        - name: DEBUG
          value: "5"
        - name: loadgame
          value: "false"
        ports:
        - name: openttd-tcp
          containerPort: 3979
          protocol: TCP
        - name: openttd-udp
          containerPort: 3979
          protocol: UDP
